name: simple_reader
description: Simple Reader

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluro: ^2.0.3
  cupertino_icons: ^1.0.2
  flutter_settings_screens: ^0.3.1-null-safety
  http: ^0.13.3
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
